app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'admin', 'middleware' => 'admin' ],function () {
	Route::get('password', 'Admins\PasswordController@password');
	Route::post('updatepassword', 'Admins\PasswordController@updatePassword');
	Route::resource('profile','Admins\ProfilesController', ['only' => [
		'index', 'edit','update'
		]]);
	Route::resource('vision-mission','Admins\VisionMissionController');
	Route::resource('image-header', 'Admins\ImageController' );
	Route::resource('history' , 'Admins\HistoryController');
	Route::controller('/','Admins\DashboardController');


});

Route::group(['middleware' => 'web'],function (){
	Route::get('/',function () {
		return view('home/index');
	});
	Route::auth();

});

app/VisionMission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VisionMission extends Model
{
  protected $table = 'vision-mission';
}

app/Http/Controllers/Admins/VisionMissionController.php
<?php

namespace App\Http\Controllers\Admins;

use App\Vision;
use App\VisionMission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Session;
class VisionMissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vision = VisionMission::all();
        return view('admin.vision-mission.index',compact('vision'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.vision-mission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = new VisionMission();

        $v->title = $request->input("title");
        $v->body = $request->input("body");

        $v->save();

        Session::flash('success','OK');
        return redirect()->route('admin.vision-mission.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $v = VisionMission::findOrFail($id);
        $v->delete();
        Session::flash('delete',' successfully deleted!');
        return Redirect::to('admin/vision-mission');
    }
}

resources/views/admin/vision-mission/create.blade.php
@extends('admin.layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">พันธกิจ</h1>


      {!! Form::open(['action'=>'Admins\VisionMissionController@store', 'files'=>true]) !!}
      <div class="form-group">
        {!! Form::label('title', 'หัวข้อ') !!}
        {{ Form::text('title', null, array('class' => 'hi-title')) }}
      </div>

      <div class="form-group">
        {!! Form::label('dbody', 'รายละเอียด') !!}
        {{ Form::textarea('body', null, array('id'=>'desc1','class' => 'ckediter')) }}
      </div>

      <div class="form-group">
        {!! Form::submit('Save', array( 'class'=>'btn btn-danger form-control' )) !!}
      </div>

      {!! Form::close() !!}
    </div>
  </div>
@endsection

resources/views/admin/vision-mission/index.blade.php
@extends('admin.layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">วิสัยทัศน์และพันธกิจ</h1> 
      <a href=" {{ url('admin/vision-mission/create')}}" class=" add pull-right"><i class="fa fa-plus fa-3x "></i></a>
    </div>
    @foreach( $vision as $v )
     <form action="{{ route('admin.vision-mission.destroy', $v->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn btn-sm btn-danger btn-de "><i class="glyphicon glyphicon-trash"></i> Delete</button>
        </form>

      <h1>{{$v->title}}</h1>
      {!!$v->body!!}
    @endforeach
  </div>


  @endsection