app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'admin', 'middleware' => 'admin' ],function () {
	Route::get('password', 'Admins\PasswordController@password');
	Route::post('updatepassword', 'Admins\PasswordController@updatePassword');
	Route::resource('profile','Admins\ProfilesController', ['only' => [
		'index', 'edit','update'
		]]);
	Route::resource('vision-mission','Admins\VisionMissionController');
	Route::resource('image-header', 'Admins\ImageController' );
	Route::resource('history' , 'Admins\HistoryController');
	Route::controller('/','Admins\DashboardController');


});

Route::group(['middleware' => 'web'],function (){
	Route::get('/',function () {
		return view('home/index');
	});
	Route::auth();

});

app/History.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class History extends Model
{
  protected $table = 'history';
}

app/Http/Controllers/Admins/HistoryController.php
<?php

namespace App\Http\Controllers\Admins;

use App\History;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Session;
use Input;
use Illuminate\Support\Facades\Redirect;
class HistoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $history = History::all();
        return view('admin.history.index',compact('history'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.history.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $history = new History();

        $history->title = $request->input("title");
        $history->detail = $request->input("detail");

        $history->save();

        Session::flash('success','successfully create history');
        return redirect()->route('admin.history.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $history = History::findOrFail($id);
        return view('admin.history.show', compact('history'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $history = History::findOrFail($id);
        return view('admin.history.edit', compact('history'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $history = History::findOrFail($id);

        $history->title = $request->input("title");
        $history->detail = $request->input("detail");

        $history->save();

        return redirect()->route('admin.history.index')->with('message', 'Item updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $history = History::findOrFail($id);
        $history->delete();
        Session::flash('delete',' successfully deleted!');
        return Redirect::to('admin/history');
    }
}

resources/views/admin/history/create.blade.php
@extends('admin.layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">ภาพหัวเว็บ</h1>

     {!! Form::open(['action'=>'Admins\HistoryController@store', 'files'=>true]) !!}
      <div class="form-group">
        {!! Form::label('title', 'หัวข้อ') !!}
        {{ Form::text('title', null, array('class' => 'hi-title')) }}
      </div>

      <div class="form-group">
        {!! Form::label('detail', 'รายละเอียด') !!}
        {{ Form::textarea('detail', null, array('id'=>'desc1','class' => 'ckeditor')) }}
      </div>

      <div class="form-group">
        {!! Form::submit('Save', array( 'class'=>'btn btn-danger form-control' )) !!}
      </div>

      {!! Form::close() !!}
    </div>
  </div>
@endsection

resources/views/admin/history/edit.blade.php
@extends('admin.layouts.app')
@section('main-content')
  {{ Form::model($history, array('class' => 'form-horizontal', 'id'=> 'my-awesome-dropzone', 'method' => 'PATCH', 'route' => array('admin.history.update', $history->id), 'files' => true)) }}
<div class="form-group">
  {!! Form::label('title', 'หัวข้อ') !!}
  {{ Form::text('title',value($history->title) , array('class'=>'form-control', 'placeholder'=>'Enter Title Here')) }}
</div>

<div class="form-group">
  {!! Form::label('detail', 'รายละเอียด') !!}
  {{ Form::textarea('detail', null, array('id'=>'desc1','class' => 'ckeditor','value'=>'$history->detail')) }}
</div>

<div class="form-group">
  {!! Form::submit('Save', array( 'class'=>'btn btn-danger form-control' )) !!}
</div>

{!! Form::close() !!}

 @endsection

resources/views/admin/history/index.blade.php
@extends('admin.layouts.app')
@section('main-content')
  <div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">ประวัติโรงเรียน</h1> <a href=" {{action('Admins\HistoryController@create')}}" class=" add pull-right"><i class="fa fa-plus fa-3x "></i></a>
  </div>

    @foreach( $history as $h )
    <a class="btn btn-xs btn-warning" href="{{ route('admin.history.edit', $h->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
    <form action="{{ route('admin.history.destroy', $h->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn btn-sm btn-danger btn-de "><i class="glyphicon glyphicon-trash"></i> Delete</button>
        </form>
        
      <h1>{{$h->title}}</h1>
      {!!$h->detail!!}
      @endforeach
    </div>
  @endsection