app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'admin', 'middleware' => 'admin' ],function () {
	Route::get('password', 'Admins\PasswordController@password');
	Route::post('updatepassword', 'Admins\PasswordController@updatePassword');
	Route::resource('profile','Admins\ProfilesController', ['only' => [
		'index', 'edit','update'
		]]);
	Route::resource('vision-mission','Admins\VisionMissionController');
	Route::resource('image-header', 'Admins\ImageController' );
	Route::resource('history' , 'Admins\HistoryController');
	Route::controller('/','Admins\DashboardController');


});

Route::group(['middleware' => 'web'],function (){
	Route::get('/',function () {
		return view('home/index');
	});
	Route::auth();

});

resources/views/admin/image-header/create.blade.php
@extends('admin.layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">ภาพหัวเว็บ</h1>
    </div>

    {!! Form::open(['action'=>'Admins\ImageController@store', 'files'=>true]) !!}

    <div class="form-group">
      {!! Form::label('image', 'Choose an image') !!}
      {!! Form::file('image') !!}
    </div>

    <div class="form-group">
      {!! Form::submit('Save', array( 'class'=>'btn btn-danger form-control' )) !!}
    </div>

    {!! Form::close() !!}
    <div class="alert-warning">
      @foreach( $errors->all() as $error )
        <br> {{ $error }}
      @endforeach
    </div>

  </div>
@endsection

resources/views/admin/image-header/index.blade.php
@extends('admin.layouts.app')
@section('main-content')
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">ภาพหัวเว็บ</h1> <a href=" {{action('Admins\ImageController@create')}}" class=" add pull-right"><i class="fa fa-plus fa-3x "></i></a>
    </div>
    @foreach( $images as $image )
      <div class="row">

        <form action="{{ route('admin.image-header.destroy', $image->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn btn-sm btn-danger btn-de "><i class="glyphicon glyphicon-trash"></i> Delete</button>
        </form>

        <div class="row header-img">
          <a href="{!! '/images/'.$image->fileName !!}">
            <img src="{!!  asset('images/' . $image->fileName) !!}"  class="img-thumbnail" >
          </a>
        </div>
      </div>
    @endforeach
    <?php echo $images->render(); ?>:
  </div>
@endsection